import { BashFile } from '../BashFile';
import { Dir } from '../Dir';

export function getUserDir(): Dir {
  const userDir = new Dir('phil');
  const scripts = new Dir('scripts');
  userDir.add(scripts);

  scripts.add(
    new BashFile('HelloWorld', ['# Hello World Script', "echo 'Hello World!'"])
  );
  scripts.add(
    new BashFile('Welcome', [
      'wait 100 -q',
      'echo "                  welcome to                "',
      'wait 100 -q',
      'echo " "',
      'wait 100 -q',
      'echo "        _     _ _            _          _ _ "',
      'wait 100 -q',
      'echo "       | |   (_) |          | |        | | |"',
      'wait 100 -q',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |"',
      'wait 100 -q',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ | |"',
      'wait 100 -q',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |"',
      'wait 100 -q',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_|"',
      'wait 100 -q',
      'echo " | |"',
      'wait 100 -q',
      'echo " |_|"',
      'wait 100 -q',
      'echo " "',
      'echo "Version"',
      'sys version',
      'echo " "',
      'echo "Need help? Type \'help\'"',
    ])
  );
  let delay = 50;
  scripts.add(
    new BashFile('Welcome2', [
      'clear',
      'sys theme random -q',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo "  "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "    "',
      'echo "    "',
      'echo "    "',
      'echo "    "',
      'echo "  _ "',
      'echo " |  "',
      'echo " | |"',
      'echo " | ."',
      'echo " | |"',
      'echo " |_|"',
      'echo "    "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "      "',
      'echo "      "',
      'echo "      "',
      'echo "      "',
      'echo "  _ __"',
      'echo " |  _ "',
      'echo " | |_)"',
      'echo " | .__"',
      'echo " | |  "',
      'echo " |_|  "',
      'echo "      "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "        "',
      'echo "        "',
      'echo "        "',
      'echo "       |"',
      'echo "  _ __ |"',
      'echo " |  _ \\"',
      'echo " | |_) |"',
      'echo " | .__/|"',
      'echo " | |    "',
      'echo " |_|    "',
      'echo "        "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "          "',
      'echo "          "',
      'echo "        _ "',
      'echo "       | |"',
      'echo "  _ __ | |"',
      'echo " |  _ \\| "',
      'echo " | |_) | |"',
      'echo " | .__/|_|"',
      'echo " | |      "',
      'echo " |_|      "',
      'echo "          "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "            "',
      'echo "            "',
      'echo "        _   "',
      'echo "       | |  "',
      'echo "  _ __ | |__"',
      'echo " |  _ \\|  _"',
      'echo " | |_) | | |"',
      'echo " | .__/|_| |"',
      'echo " | |        "',
      'echo " |_|        "',
      'echo "            "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "              "',
      'echo "              "',
      'echo "        _     "',
      'echo "       | |   ("',
      'echo "  _ __ | |__  "',
      'echo " |  _ \\|  _  "',
      'echo " | |_) | | | |"',
      'echo " | .__/|_| |_|"',
      'echo " | |          "',
      'echo " |_|          "',
      'echo "              "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                "',
      'echo "                "',
      'echo "        _     _ "',
      'echo "       | |   (_)"',
      'echo "  _ __ | |__  _|"',
      'echo " |  _ \\|  _ \\|"',
      'echo " | |_) | | | | |"',
      'echo " | .__/|_| |_|_|"',
      'echo " | |            "',
      'echo " |_|            "',
      'echo "                "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  "',
      'echo "                  "',
      'echo "        _     _ _ "',
      'echo "       | |   (_) |"',
      'echo "  _ __ | |__  _| |"',
      'echo " |  _ \\|  _ \\| |"',
      'echo " | |_) | | | | | |"',
      'echo " | .__/|_| |_|_|_|"',
      'echo " | |              "',
      'echo " |_|              "',
      'echo "                  "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  we"',
      'echo "                    "',
      'echo "        _     _ _   "',
      'echo "       | |   (_) |  "',
      'echo "  _ __ | |__  _| |__"',
      'echo " |  _ \\|  _ \\| | |"',
      'echo " | |_) | | | | | |  "',
      'echo " | .__/|_| |_|_|_|  "',
      'echo " | |                "',
      'echo " |_|                "',
      'echo "                    "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welc"',
      'echo "                      "',
      'echo "        _     _ _     "',
      'echo "       | |   (_) |    "',
      'echo "  _ __ | |__  _| |____"',
      'echo " |  _ \\|  _ \\| | |__"',
      'echo " | |_) | | | | | |    "',
      'echo " | .__/|_| |_|_|_|    "',
      'echo " | |                  "',
      'echo " |_|                  "',
      'echo "                      "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcom"',
      'echo "                        "',
      'echo "        _     _ _       "',
      'echo "       | |   (_) |      "',
      'echo "  _ __ | |__  _| |______"',
      'echo " |  _ \\|  _ \\| | |____"',
      'echo " | |_) | | | | | |      "',
      'echo " | .__/|_| |_|_|_|      "',
      'echo " | |                    "',
      'echo " |_|                    "',
      'echo "                        "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcome "',
      'echo "                          "',
      'echo "        _     _ _         "',
      'echo "       | |   (_) |        "',
      'echo "  _ __ | |__  _| |______ _"',
      'echo " |  _ \\|  _ \\| | |______"',
      'echo " | |_) | | | | | |      \\"',
      'echo " | .__/|_| |_|_|_|      |_"',
      'echo " | |                      "',
      'echo " |_|                      "',
      'echo "                          "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcome to"',
      'echo "                            "',
      'echo "        _     _ _           "',
      'echo "       | |   (_) |          "',
      'echo "  _ __ | |__  _| |______ ___"',
      'echo " |  _ \\|  _ \\| | |______/ "',
      'echo " | |_) | | | | | |      \\__"',
      'echo " | .__/|_| |_|_|_|      |___"',
      'echo " | |                        "',
      'echo " |_|                        "',
      'echo "                            "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to  "',
      'echo "                              "',
      'echo "        _     _ _            _"',
      'echo "       | |   (_) |          | "',
      'echo "  _ __ | |__  _| |______ ___| "',
      'echo " |  _ \\|  _ \\| | |______/ __"',
      'echo " | |_) | | | | | |      \\__  "',
      'echo " | .__/|_| |_|_|_|      |___/_"',
      'echo " | |                          "',
      'echo " |_|                          "',
      'echo "                              "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to    "',
      'echo "                                "',
      'echo "        _     _ _            _  "',
      'echo "       | |   (_) |          | | "',
      'echo "  _ __ | |__  _| |______ ___| |_"',
      'echo " |  _ \\|  _ \\| | |______/ __| "',
      'echo " | |_) | | | | | |      \\__ \\ "',
      'echo " | .__/|_| |_|_|_|      |___/_| "',
      'echo " | |                            "',
      'echo " |_|                            "',
      'echo "                                "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to      "',
      'echo "                                  "',
      'echo "        _     _ _            _    "',
      'echo "       | |   (_) |          | |   "',
      'echo "  _ __ | |__  _| |______ ___| |__ "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _"',
      'echo " | |_) | | | | | |      \\__ \\ | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_"',
      'echo " | |                              "',
      'echo " |_|                              "',
      'echo "                                  "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to        "',
      'echo "                                    "',
      'echo "        _     _ _            _      "',
      'echo "       | |   (_) |          | |     "',
      'echo "  _ __ | |__  _| |______ ___| |__   "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _  "',
      'echo " | |_) | | | | | |      \\__ \\ | | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_| "',
      'echo " | |                                "',
      'echo " |_|                                "',
      'echo "                                    "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to          "',
      'echo "                                      "',
      'echo "        _     _ _            _        "',
      'echo "       | |   (_) |          | |       "',
      'echo "  _ __ | |__  _| |______ ___| |__   __"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ "',
      'echo " | |_) | | | | | |      \\__ \\ | | | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\_"',
      'echo " | |                                  "',
      'echo " |_|                                  "',
      'echo "                                      "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to            "',
      'echo "                                        "',
      'echo "        _     _ _            _          "',
      'echo "       | |   (_) |          | |        |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___|"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / "',
      'echo " | |_) | | | | | |      \\__ \\ | | |  _"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___"',
      'echo " | |                                    "',
      'echo " |_|                                    "',
      'echo "                                        "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to              "',
      'echo "                                          "',
      'echo "        _     _ _            _          _ "',
      'echo "       | |   (_) |          | |        | |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| |"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ "',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_"',
      'echo " | |                                      "',
      'echo " |_|                                      "',
      'echo "                                          "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                "',
      'echo "                                            "',
      'echo "        _     _ _            _          _ _ "',
      'echo "       | |   (_) |          | |        | | |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ |"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_"',
      'echo " | |                                        "',
      'echo " |_|                                        "',
      'echo "                                            "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                  "',
      'echo "                                              "',
      'echo "        _     _ _            _          _ _   "',
      'echo "       | |   (_) |          | |        | | |  "',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |  "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ |"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_| "',
      'echo " | |                                          "',
      'echo " |_|                                          "',
      'echo "                                              "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                    "',
      'echo "                                                "',
      'echo "        _     _ _            _          _ _     "',
      'echo "       | |   (_) |          | |        | | |    "',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |    "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ | |"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |  "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_|   "',
      'echo " | |                                            "',
      'echo " |_|                                            "',
      'echo "                                                "',
      'wait ' + delay + ' -q',

      'echo "Version"',
      'sys version',
      'echo " "',
      'echo "Need help? Type \'help\'"',
    ])
  );

  const projects = new Dir('projects');
  const skills = new Dir('skills');
  const contact = new Dir('contact');
  const about = new Dir('about');

  userDir.addEntries([projects, skills, contact, about]);
  return userDir;
}
