import { BashFile } from '../BashFile';
import { Dir } from '../Dir';
import { File } from '../File';

export function getUserDir(): Dir {
  const userDir = new Dir('phil');
  const scripts = new Dir('scripts');
  userDir.add(scripts);

  scripts.add(
    new BashFile('HelloWorld', ['# Hello World Script', "echo 'Hello World!'"])
  );
  scripts.add(
    new BashFile('Welcome', [
      'wait 100 -q',
      'echo "                  welcome to                "',
      'wait 100 -q',
      'echo " "',
      'wait 100 -q',
      'echo "        _     _ _            _          _ _ "',
      'wait 100 -q',
      'echo "       | |   (_) |          | |        | | |"',
      'wait 100 -q',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |"',
      'wait 100 -q',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ | |"',
      'wait 100 -q',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |"',
      'wait 100 -q',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_|"',
      'wait 100 -q',
      'echo " | |"',
      'wait 100 -q',
      'echo " |_|"',
      'wait 100 -q',
      'echo " "',
      'echo "Version"',
      'sys version',
      'echo " "',
      'echo "Need help? Type \'help\'"',
    ])
  );
  let delay = 50;
  scripts.add(
    new BashFile('Welcome2', [
      'clear',
      'sys theme random -q',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'echo " "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo "  "',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo " |"',
      'echo "  "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "    "',
      'echo "    "',
      'echo "    "',
      'echo "    "',
      'echo "  _ "',
      'echo " |  "',
      'echo " | |"',
      'echo " | ."',
      'echo " | |"',
      'echo " |_|"',
      'echo "    "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "      "',
      'echo "      "',
      'echo "      "',
      'echo "      "',
      'echo "  _ __"',
      'echo " |  _ "',
      'echo " | |_)"',
      'echo " | .__"',
      'echo " | |  "',
      'echo " |_|  "',
      'echo "      "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "        "',
      'echo "        "',
      'echo "        "',
      'echo "       |"',
      'echo "  _ __ |"',
      'echo " |  _ \\"',
      'echo " | |_) |"',
      'echo " | .__/|"',
      'echo " | |    "',
      'echo " |_|    "',
      'echo "        "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "          "',
      'echo "          "',
      'echo "        _ "',
      'echo "       | |"',
      'echo "  _ __ | |"',
      'echo " |  _ \\| "',
      'echo " | |_) | |"',
      'echo " | .__/|_|"',
      'echo " | |      "',
      'echo " |_|      "',
      'echo "          "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "            "',
      'echo "            "',
      'echo "        _   "',
      'echo "       | |  "',
      'echo "  _ __ | |__"',
      'echo " |  _ \\|  _"',
      'echo " | |_) | | |"',
      'echo " | .__/|_| |"',
      'echo " | |        "',
      'echo " |_|        "',
      'echo "            "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "              "',
      'echo "              "',
      'echo "        _     "',
      'echo "       | |   ("',
      'echo "  _ __ | |__  "',
      'echo " |  _ \\|  _  "',
      'echo " | |_) | | | |"',
      'echo " | .__/|_| |_|"',
      'echo " | |          "',
      'echo " |_|          "',
      'echo "              "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                "',
      'echo "                "',
      'echo "        _     _ "',
      'echo "       | |   (_)"',
      'echo "  _ __ | |__  _|"',
      'echo " |  _ \\|  _ \\|"',
      'echo " | |_) | | | | |"',
      'echo " | .__/|_| |_|_|"',
      'echo " | |            "',
      'echo " |_|            "',
      'echo "                "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  "',
      'echo "                  "',
      'echo "        _     _ _ "',
      'echo "       | |   (_) |"',
      'echo "  _ __ | |__  _| |"',
      'echo " |  _ \\|  _ \\| |"',
      'echo " | |_) | | | | | |"',
      'echo " | .__/|_| |_|_|_|"',
      'echo " | |              "',
      'echo " |_|              "',
      'echo "                  "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  we"',
      'echo "                    "',
      'echo "        _     _ _   "',
      'echo "       | |   (_) |  "',
      'echo "  _ __ | |__  _| |__"',
      'echo " |  _ \\|  _ \\| | |"',
      'echo " | |_) | | | | | |  "',
      'echo " | .__/|_| |_|_|_|  "',
      'echo " | |                "',
      'echo " |_|                "',
      'echo "                    "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welc"',
      'echo "                      "',
      'echo "        _     _ _     "',
      'echo "       | |   (_) |    "',
      'echo "  _ __ | |__  _| |____"',
      'echo " |  _ \\|  _ \\| | |__"',
      'echo " | |_) | | | | | |    "',
      'echo " | .__/|_| |_|_|_|    "',
      'echo " | |                  "',
      'echo " |_|                  "',
      'echo "                      "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcom"',
      'echo "                        "',
      'echo "        _     _ _       "',
      'echo "       | |   (_) |      "',
      'echo "  _ __ | |__  _| |______"',
      'echo " |  _ \\|  _ \\| | |____"',
      'echo " | |_) | | | | | |      "',
      'echo " | .__/|_| |_|_|_|      "',
      'echo " | |                    "',
      'echo " |_|                    "',
      'echo "                        "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcome "',
      'echo "                          "',
      'echo "        _     _ _         "',
      'echo "       | |   (_) |        "',
      'echo "  _ __ | |__  _| |______ _"',
      'echo " |  _ \\|  _ \\| | |______"',
      'echo " | |_) | | | | | |      \\"',
      'echo " | .__/|_| |_|_|_|      |_"',
      'echo " | |                      "',
      'echo " |_|                      "',
      'echo "                          "',
      'wait ' + delay + ' -q',
      'clear',
      'echo "                  welcome to"',
      'echo "                            "',
      'echo "        _     _ _           "',
      'echo "       | |   (_) |          "',
      'echo "  _ __ | |__  _| |______ ___"',
      'echo " |  _ \\|  _ \\| | |______/ "',
      'echo " | |_) | | | | | |      \\__"',
      'echo " | .__/|_| |_|_|_|      |___"',
      'echo " | |                        "',
      'echo " |_|                        "',
      'echo "                            "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to  "',
      'echo "                              "',
      'echo "        _     _ _            _"',
      'echo "       | |   (_) |          | "',
      'echo "  _ __ | |__  _| |______ ___| "',
      'echo " |  _ \\|  _ \\| | |______/ __"',
      'echo " | |_) | | | | | |      \\__  "',
      'echo " | .__/|_| |_|_|_|      |___/_"',
      'echo " | |                          "',
      'echo " |_|                          "',
      'echo "                              "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to    "',
      'echo "                                "',
      'echo "        _     _ _            _  "',
      'echo "       | |   (_) |          | | "',
      'echo "  _ __ | |__  _| |______ ___| |_"',
      'echo " |  _ \\|  _ \\| | |______/ __| "',
      'echo " | |_) | | | | | |      \\__ \\ "',
      'echo " | .__/|_| |_|_|_|      |___/_| "',
      'echo " | |                            "',
      'echo " |_|                            "',
      'echo "                                "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to      "',
      'echo "                                  "',
      'echo "        _     _ _            _    "',
      'echo "       | |   (_) |          | |   "',
      'echo "  _ __ | |__  _| |______ ___| |__ "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _"',
      'echo " | |_) | | | | | |      \\__ \\ | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_"',
      'echo " | |                              "',
      'echo " |_|                              "',
      'echo "                                  "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to        "',
      'echo "                                    "',
      'echo "        _     _ _            _      "',
      'echo "       | |   (_) |          | |     "',
      'echo "  _ __ | |__  _| |______ ___| |__   "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _  "',
      'echo " | |_) | | | | | |      \\__ \\ | | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_| "',
      'echo " | |                                "',
      'echo " |_|                                "',
      'echo "                                    "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to          "',
      'echo "                                      "',
      'echo "        _     _ _            _        "',
      'echo "       | |   (_) |          | |       "',
      'echo "  _ __ | |__  _| |______ ___| |__   __"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ "',
      'echo " | |_) | | | | | |      \\__ \\ | | | "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\_"',
      'echo " | |                                  "',
      'echo " |_|                                  "',
      'echo "                                      "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to            "',
      'echo "                                        "',
      'echo "        _     _ _            _          "',
      'echo "       | |   (_) |          | |        |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___|"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / "',
      'echo " | |_) | | | | | |      \\__ \\ | | |  _"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___"',
      'echo " | |                                    "',
      'echo " |_|                                    "',
      'echo "                                        "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to              "',
      'echo "                                          "',
      'echo "        _     _ _            _          _ "',
      'echo "       | |   (_) |          | |        | |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| |"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ "',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_"',
      'echo " | |                                      "',
      'echo " |_|                                      "',
      'echo "                                          "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                "',
      'echo "                                            "',
      'echo "        _     _ _            _          _ _ "',
      'echo "       | |   (_) |          | |        | | |"',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |"',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ |"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_"',
      'echo " | |                                        "',
      'echo " |_|                                        "',
      'echo "                                            "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                  "',
      'echo "                                              "',
      'echo "        _     _ _            _          _ _   "',
      'echo "       | |   (_) |          | |        | | |  "',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |  "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ |"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |"',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_| "',
      'echo " | |                                          "',
      'echo " |_|                                          "',
      'echo "                                              "',
      'wait ' + delay + ' -q',

      'clear',
      'echo "                  welcome to                    "',
      'echo "                                                "',
      'echo "        _     _ _            _          _ _     "',
      'echo "       | |   (_) |          | |        | | |    "',
      'echo "  _ __ | |__  _| |______ ___| |__   ___| | |    "',
      'echo " |  _ \\|  _ \\| | |______/ __|  _ \\ / _ \\ | |"',
      'echo " | |_) | | | | | |      \\__ \\ | | |  __/ | |  "',
      'echo " | .__/|_| |_|_|_|      |___/_| |_|\\___|_|_|   "',
      'echo " | |                                            "',
      'echo " |_|                                            "',
      'echo "                                                "',
      'wait ' + delay + ' -q',

      'echo "Version"',
      'sys version',
      'echo " "',
      'echo "Need help? Type \'help\'"',
    ])
  );

  const projects = new Dir('projects');
  /* projects.add(
    new BashFile('projects', [
      '# Install echo advanced package',
      'pxm install echoa -q',
      ' ',
      'echo My Projects:',
      'echo " "',
      'echoc red OwnObjectScriptExtension',
      'echo "A Visual Studio Code extension that supplies tools for InterSystems ObjectScript"',
      'echol https://github.com/cophilot/ownobjectscriptextension View on GitHub',
      'echo " "',
      'echoc red OwnGitExtension',
      'echo "A Visual Studio Code extension that offers tools for working with GitHub projects"',
      'echol https://github.com/cophilot/owngitextension View on GitHub',
      'echo " "',
      'echoc red VSToolKit',
      'echo "Providing tools for Visual Studio Code"',
      'echol https://github.com/cophilot/VSToolKit View on GitHub',
      'echo " "',
      'echoc red Petgram',
      'echo "Nothing to see here, just a social media site for pets"',
      'echol https://petgram.philipp-bonin.com/ Try',
      'echo " "',
      'echoc red Color Chicken',
      'echo "Be a feathered chameleon, master the hurdles in color chicken"',
      'echol https://colorchicken.philipp-bonin.com/ Try',
      'echo " "',
      'echoc red OrbitLab',
      'echo "A webapplication to simulate orbits"',
      'echol https://orbitlab.philipp-bonin.com/ Try',
      'echo " "',
      'echol https://github.com/cophilot View my GitHub profile to see more projects',
      'echo " "',
    ])
  ); */

  fetch(
    'https://raw.githubusercontent.com/cophilot/.project-provider/main/projects.json'
  ).then((resp) =>
    resp.json().then((json) => {
      projects.add(
        new File('projects.json', JSON.stringify(json, null, 2).split('\n'))
      );
    })
  );

  const skills = new Dir('skills');
  skills.add(
    new File('skills.py', [
      'from programming_languages import Python, Java, JavaScript, TypeScript, SASS, Go, C++, SQL, Rust',
      'from frameworks import Angular, React, Vue',
      'from databases import InterSystems_IRIS, PostgreSQL',
      'from tools import Git, Docker, VSCode, Postman, NodeRED, NodeJS, npm, Vite',
      'from other import Linux, SAP',
      'from languages import German, English',
      ' ',
      'print("To be continued...")',
      ' ',
    ])
  );
  const contact = new Dir('contact');
  contact.add(
    new File('contact.html', [
      '<html>',
      '  <head>',
      '    <title>Phil Contact</title>',
      '  </head>',
      '  <body>',
      '    <h1>Contact</h1>',
      '    <ul>',
      '      <li>',
      '        <a href="mailto:info@philipp-bonin.com">E-Mail</a>',
      '      </li>',
      '      <li>',
      '        <a href="https://github.com/cophilot">GitHub</a>',
      '      </li>',
      '    </ul>',
      '  </body>',
      '</html>',
    ])
  );
  const about = new Dir('about-me');
  about.add(
    new File('Student.java', [
      'public class Student implements Nationality<German> {',
      ' ',
      '    private final String name;',
      '    private int age;',
      '    private String major;',
      '    private String university;',
      '    private Job job;',
      '    private final boolean lovesDogs;',
      ' ',
      '    public Student(){',
      '        this.name = "Philipp";',
      '        this.age = 23;',
      '        this.major = "Computer Science B.Sc.";',
      '        this.university = "Technical University of Darmstadt";',
      '        this.job = new Job("Software Developer", "CQSE");',
      '        this.lovesDogs = true;',
      '    }',
      ' ',
      '    @Override',
      '    public String sayHello() {',
      '        return "Hallo!";',
      '    }',
      ' ',
      '}',
    ])
  );

  userDir.addEntries([projects, skills, contact, about]);
  return userDir;
}
